;;; fix.el --- FIX protcol parsing for emacs

;; Copyright (C) 2016 Free Software Foundation, Inc.
;;
;; Author: Andrew Gavin <andy.gavin@acm.org>
;; Maintainer: Andrew Gavin <andy.gavin@acm.org>
;; Created: 09 Sep 2016
;; Version: 0.01
;; Keywords: trading fix

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program; if not, write to the Free Software
;; Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

;;; Commentary:

;; This is a first attempt to get the basic machanics of a fix message decoder working.
;; It doesn't do very much except give the tag values a message passed into the decode
;; function and a description of what that field means when populated.  It needs a few things
;; to be practical
;; - An idea of which tags form part of a message.
;; - Decoding of enum types giving meaning to codes when presented in fields.
;; - Different FIX spedifications.
;; Then what would be nice is:
;; - Some commentry on the meaning.
;; - Be able to analyse a sequence of messages.

;; Put this file into your load-path and the following into your ~/.emacs:
;;   (require 'fix)

;;; Code:

(eval-when-compile
  (require 'cl))

(defclass fix-tag-descriptor ()
  ((description  :initarg :description
                 :initform ""
                 :type string
                 :documentation "The description of the tag.")
   (tag :initarg :name
        :initform ""
        :type string
        :documentation "The name of the tag.")
   ))

(defvar fix-test-tags)
(defvar fix-field-separator-re "[\C-a]" "Field separator characters.")
(defvar fix-tag-separator-re "[=]" "Field separator characters.")


(setq fix-test-tags `(
                        (1 . ,(fix-tag-descriptor :name "Account" :description ""))
  (2 . ,(fix-tag-descriptor :name "AdvId" :description ""))
  (3 . ,(fix-tag-descriptor :name "AdvRefID" :description ""))
  (4 . ,(fix-tag-descriptor :name "AdvSide" :description ""))
  (5 . ,(fix-tag-descriptor :name "AdvTransType" :description ""))
  (6 . ,(fix-tag-descriptor :name "AvgPx" :description ""))
  (7 . ,(fix-tag-descriptor :name "BeginSeqNo" :description ""))
  (8 . ,(fix-tag-descriptor :name "BeginString" :description ""))
  (9 . ,(fix-tag-descriptor :name "BodyLength" :description ""))
  (10 . ,(fix-tag-descriptor :name "CheckSum" :description ""))
  (11 . ,(fix-tag-descriptor :name "ClOrdID" :description ""))
  (12 . ,(fix-tag-descriptor :name "Commission" :description ""))
  (13 . ,(fix-tag-descriptor :name "CommType" :description ""))
  (14 . ,(fix-tag-descriptor :name "CumQty" :description ""))
  (15 . ,(fix-tag-descriptor :name "Currency" :description ""))
  (16 . ,(fix-tag-descriptor :name "EndSeqNo" :description ""))
  (17 . ,(fix-tag-descriptor :name "ExecID" :description ""))
  (18 . ,(fix-tag-descriptor :name "ExecInst" :description ""))
  (19 . ,(fix-tag-descriptor :name "ExecRefID" :description ""))
  (20 . ,(fix-tag-descriptor :name "ExecTransType" :description ""))
  (21 . ,(fix-tag-descriptor :name "HandlInst" :description ""))
  (22 . ,(fix-tag-descriptor :name "IDSource" :description ""))
  (23 . ,(fix-tag-descriptor :name "IOIid" :description ""))
  (24 . ,(fix-tag-descriptor :name "IOIOthSvc" :description ""))
  (25 . ,(fix-tag-descriptor :name "IOIQltyInd" :description ""))
  (26 . ,(fix-tag-descriptor :name "IOIRefID" :description ""))
  (27 . ,(fix-tag-descriptor :name "IOIShares" :description ""))
  (28 . ,(fix-tag-descriptor :name "IOITransType" :description ""))
  (29 . ,(fix-tag-descriptor :name "LastCapacity" :description ""))
  (30 . ,(fix-tag-descriptor :name "LastMkt" :description ""))
  (31 . ,(fix-tag-descriptor :name "LastPx" :description ""))
  (32 . ,(fix-tag-descriptor :name "LastShares" :description ""))
  (33 . ,(fix-tag-descriptor :name "LinesOfText" :description ""))
  (34 . ,(fix-tag-descriptor :name "MsgSeqNum" :description ""))
  (35 . ,(fix-tag-descriptor :name "MsgType" :description ""))
  (36 . ,(fix-tag-descriptor :name "NewSeqNo" :description ""))
  (37 . ,(fix-tag-descriptor :name "OrderID" :description ""))
  (38 . ,(fix-tag-descriptor :name "OrderQty" :description ""))
  (39 . ,(fix-tag-descriptor :name "OrdStatus" :description ""))
  (40 . ,(fix-tag-descriptor :name "OrdType" :description ""))
  (41 . ,(fix-tag-descriptor :name "OrigClOrdID" :description ""))
  (42 . ,(fix-tag-descriptor :name "OrigTime" :description ""))
  (43 . ,(fix-tag-descriptor :name "PossDupFlag" :description ""))
  (44 . ,(fix-tag-descriptor :name "Price" :description ""))
  (45 . ,(fix-tag-descriptor :name "RefSeqNum" :description ""))
  (46 . ,(fix-tag-descriptor :name "RelatdSym" :description ""))
  (47 . ,(fix-tag-descriptor :name "Rule80A" :description ""))
  (48 . ,(fix-tag-descriptor :name "SecurityID" :description ""))
  (49 . ,(fix-tag-descriptor :name "SenderCompID" :description ""))
  (50 . ,(fix-tag-descriptor :name "SenderSubID" :description ""))
  (51 . ,(fix-tag-descriptor :name "SendingDate" :description ""))
  (52 . ,(fix-tag-descriptor :name "SendingTime" :description ""))
  (53 . ,(fix-tag-descriptor :name "Shares" :description ""))
  (54 . ,(fix-tag-descriptor :name "Side" :description ""))
  (55 . ,(fix-tag-descriptor :name "Symbol" :description ""))
  (56 . ,(fix-tag-descriptor :name "TargetCompID" :description ""))
  (57 . ,(fix-tag-descriptor :name "TargetSubID" :description ""))
  (58 . ,(fix-tag-descriptor :name "Text" :description ""))
  (59 . ,(fix-tag-descriptor :name "TimeInForce" :description ""))
  (60 . ,(fix-tag-descriptor :name "TransactTime" :description ""))
  (61 . ,(fix-tag-descriptor :name "Urgency" :description ""))
  (62 . ,(fix-tag-descriptor :name "ValidUntilTime" :description ""))
  (63 . ,(fix-tag-descriptor :name "SettlmntTyp" :description ""))
  (64 . ,(fix-tag-descriptor :name "FutSettDate" :description ""))
  (65 . ,(fix-tag-descriptor :name "SymbolSfx" :description ""))
  (66 . ,(fix-tag-descriptor :name "ListID" :description ""))
  (67 . ,(fix-tag-descriptor :name "ListSeqNo" :description ""))
  (68 . ,(fix-tag-descriptor :name "TotNoOrders" :description ""))
  (69 . ,(fix-tag-descriptor :name "ListExecInst" :description ""))
  (70 . ,(fix-tag-descriptor :name "AllocID" :description ""))
  (71 . ,(fix-tag-descriptor :name "AllocTransType" :description ""))
  (72 . ,(fix-tag-descriptor :name "RefAllocID" :description ""))
  (73 . ,(fix-tag-descriptor :name "NoOrders" :description ""))
  (74 . ,(fix-tag-descriptor :name "AvgPrxPrecision" :description ""))
  (75 . ,(fix-tag-descriptor :name "TradeDate" :description ""))
  (76 . ,(fix-tag-descriptor :name "ExecBroker" :description ""))
  (77 . ,(fix-tag-descriptor :name "OpenClose" :description ""))
  (78 . ,(fix-tag-descriptor :name "NoAllocs" :description ""))
  (79 . ,(fix-tag-descriptor :name "AllocAccount" :description ""))
  (80 . ,(fix-tag-descriptor :name "AllocShares" :description ""))
  (81 . ,(fix-tag-descriptor :name "ProcessCode" :description ""))
  (82 . ,(fix-tag-descriptor :name "NoRpts" :description ""))
  (83 . ,(fix-tag-descriptor :name "RptSeq" :description ""))
  (84 . ,(fix-tag-descriptor :name "CxlQty" :description ""))
  (85 . ,(fix-tag-descriptor :name "NoDlvyInst" :description ""))
  (86 . ,(fix-tag-descriptor :name "DlvyInst" :description ""))
  (87 . ,(fix-tag-descriptor :name "AllocStatus" :description ""))
  (88 . ,(fix-tag-descriptor :name "AllocRejCode" :description ""))
  (89 . ,(fix-tag-descriptor :name "Signature" :description ""))
  (90 . ,(fix-tag-descriptor :name "SecureDataLen" :description ""))
  (91 . ,(fix-tag-descriptor :name "SecureData" :description ""))
  (92 . ,(fix-tag-descriptor :name "BrokerOfCredit" :description ""))
  (93 . ,(fix-tag-descriptor :name "SignatureLength" :description ""))
  (94 . ,(fix-tag-descriptor :name "EmailType" :description ""))
  (95 . ,(fix-tag-descriptor :name "RawDataLength" :description ""))
  (96 . ,(fix-tag-descriptor :name "RawData" :description ""))
  (97 . ,(fix-tag-descriptor :name "PossResend" :description ""))
  (98 . ,(fix-tag-descriptor :name "EncryptMethod" :description ""))
  (99 . ,(fix-tag-descriptor :name "StopPx" :description ""))
  (100 . ,(fix-tag-descriptor :name "ExDestination" :description ""))
  (102 . ,(fix-tag-descriptor :name "CxlRejReason" :description ""))
  (103 . ,(fix-tag-descriptor :name "OrdRejReason" :description ""))
  (104 . ,(fix-tag-descriptor :name "IOIQualifier" :description ""))
  (105 . ,(fix-tag-descriptor :name "WaveNo" :description ""))
  (106 . ,(fix-tag-descriptor :name "Issuer" :description ""))
  (107 . ,(fix-tag-descriptor :name "SecurityDesc" :description ""))
  (108 . ,(fix-tag-descriptor :name "HeartBtInt" :description ""))
  (109 . ,(fix-tag-descriptor :name "ClientID" :description ""))
  (110 . ,(fix-tag-descriptor :name "MinQty" :description ""))
  (111 . ,(fix-tag-descriptor :name "MaxFloor" :description ""))
  (112 . ,(fix-tag-descriptor :name "TestReqID" :description ""))
  (113 . ,(fix-tag-descriptor :name "ReportToExch" :description ""))
  (114 . ,(fix-tag-descriptor :name "LocateReqd" :description ""))
  (115 . ,(fix-tag-descriptor :name "OnBehalfOfCompID" :description ""))
  (116 . ,(fix-tag-descriptor :name "OnBehalfOfSubID" :description ""))
  (117 . ,(fix-tag-descriptor :name "QuoteID" :description ""))
  (118 . ,(fix-tag-descriptor :name "NetMoney" :description ""))
  (119 . ,(fix-tag-descriptor :name "SettlCurrAmt" :description ""))
  (120 . ,(fix-tag-descriptor :name "SettlCurrency" :description ""))
  (121 . ,(fix-tag-descriptor :name "ForexReq" :description ""))
  (122 . ,(fix-tag-descriptor :name "OrigSendingTime" :description ""))
  (123 . ,(fix-tag-descriptor :name "GapFillFlag" :description ""))
  (124 . ,(fix-tag-descriptor :name "NoExecs" :description ""))
  (125 . ,(fix-tag-descriptor :name "CxlType" :description ""))
  (126 . ,(fix-tag-descriptor :name "ExpireTime" :description ""))
  (127 . ,(fix-tag-descriptor :name "DKReason" :description ""))
  (128 . ,(fix-tag-descriptor :name "DeliverToCompID" :description ""))
  (129 . ,(fix-tag-descriptor :name "DeliverToSubID" :description ""))
  (130 . ,(fix-tag-descriptor :name "IOINaturalFlag" :description ""))
  (131 . ,(fix-tag-descriptor :name "QuoteReqID" :description ""))
  (132 . ,(fix-tag-descriptor :name "BidPx" :description ""))
  (133 . ,(fix-tag-descriptor :name "OfferPx" :description ""))
  (134 . ,(fix-tag-descriptor :name "BidSize" :description ""))
  (135 . ,(fix-tag-descriptor :name "OfferSize" :description ""))
  (136 . ,(fix-tag-descriptor :name "NoMiscFees" :description ""))
  (137 . ,(fix-tag-descriptor :name "MiscFeeAmt" :description ""))
  (138 . ,(fix-tag-descriptor :name "MiscFeeCurr" :description ""))
  (139 . ,(fix-tag-descriptor :name "MiscFeeType" :description ""))
  (140 . ,(fix-tag-descriptor :name "PrevClosePx" :description ""))
  (141 . ,(fix-tag-descriptor :name "ResetSeqNumFlag" :description ""))
  (142 . ,(fix-tag-descriptor :name "SenderLocationID" :description ""))
  (143 . ,(fix-tag-descriptor :name "TargetLocationID" :description ""))
  (144 . ,(fix-tag-descriptor :name "OnBehalfOfLocationID" :description ""))
  (145 . ,(fix-tag-descriptor :name "DeliverToLocationID" :description ""))
  (146 . ,(fix-tag-descriptor :name "NoRelatedSym" :description ""))
  (147 . ,(fix-tag-descriptor :name "Subject" :description ""))
  (148 . ,(fix-tag-descriptor :name "Headline" :description ""))
  (149 . ,(fix-tag-descriptor :name "URLLink" :description ""))
  (150 . ,(fix-tag-descriptor :name "ExecType" :description ""))
  (151 . ,(fix-tag-descriptor :name "LeavesQty" :description ""))
  (152 . ,(fix-tag-descriptor :name "CashOrderQty" :description ""))
  (153 . ,(fix-tag-descriptor :name "AllocAvgPx" :description ""))
  (154 . ,(fix-tag-descriptor :name "AllocNetMoney" :description ""))
  (155 . ,(fix-tag-descriptor :name "SettlCurrFxRate" :description ""))
  (156 . ,(fix-tag-descriptor :name "SettlCurrFxRateCalc" :description ""))
  (157 . ,(fix-tag-descriptor :name "NumDaysInterest" :description ""))
  (158 . ,(fix-tag-descriptor :name "AccruedInterestRate" :description ""))
  (159 . ,(fix-tag-descriptor :name "AccruedInterestAmt" :description ""))
  (160 . ,(fix-tag-descriptor :name "SettlInstMode" :description ""))
  (161 . ,(fix-tag-descriptor :name "AllocText" :description ""))
  (162 . ,(fix-tag-descriptor :name "SettlInstID" :description ""))
  (163 . ,(fix-tag-descriptor :name "SettlInstTransType" :description ""))
  (164 . ,(fix-tag-descriptor :name "EmailThreadID" :description ""))
  (165 . ,(fix-tag-descriptor :name "SettlInstSource" :description ""))
  (166 . ,(fix-tag-descriptor :name "SettlLocation" :description ""))
  (167 . ,(fix-tag-descriptor :name "SecurityType" :description ""))
  (168 . ,(fix-tag-descriptor :name "EffectiveTime" :description ""))
  (169 . ,(fix-tag-descriptor :name "StandInstDbType" :description ""))
  (170 . ,(fix-tag-descriptor :name "StandInstDbName" :description ""))
  (171 . ,(fix-tag-descriptor :name "StandInstDbID" :description ""))
  (172 . ,(fix-tag-descriptor :name "SettlDeliveryType" :description ""))
  (173 . ,(fix-tag-descriptor :name "SettlDepositoryCode" :description ""))
  (174 . ,(fix-tag-descriptor :name "SettlBrkrCode" :description ""))
  (175 . ,(fix-tag-descriptor :name "SettlInstCode" :description ""))
  (176 . ,(fix-tag-descriptor :name "SecuritySettlAgentName" :description ""))
  (177 . ,(fix-tag-descriptor :name "SecuritySettlAgentCode" :description ""))
  (178 . ,(fix-tag-descriptor :name "SecuritySettlAgentAcctNum" :description ""))
  (179 . ,(fix-tag-descriptor :name "SecuritySettlAgentAcctName" :description ""))
  (180 . ,(fix-tag-descriptor :name "SecuritySettlAgentContactName" :description ""))
  (181 . ,(fix-tag-descriptor :name "SecuritySettlAgentContactPhone" :description ""))
  (182 . ,(fix-tag-descriptor :name "CashSettlAgentName" :description ""))
  (183 . ,(fix-tag-descriptor :name "CashSettlAgentCode" :description ""))
  (184 . ,(fix-tag-descriptor :name "CashSettlAgentAcctNum" :description ""))
  (185 . ,(fix-tag-descriptor :name "CashSettlAgentAcctName" :description ""))
  (186 . ,(fix-tag-descriptor :name "CashSettlAgentContactName" :description ""))
  (187 . ,(fix-tag-descriptor :name "CashSettlAgentContactPhone" :description ""))
  (188 . ,(fix-tag-descriptor :name "BidSpotRate" :description ""))
  (189 . ,(fix-tag-descriptor :name "BidForwardPoints" :description ""))
  (190 . ,(fix-tag-descriptor :name "OfferSpotRate" :description ""))
  (191 . ,(fix-tag-descriptor :name "OfferForwardPoints" :description ""))
  (192 . ,(fix-tag-descriptor :name "OrderQty2" :description ""))
  (193 . ,(fix-tag-descriptor :name "FutSettDate2" :description ""))
  (194 . ,(fix-tag-descriptor :name "LastSpotRate" :description ""))
  (195 . ,(fix-tag-descriptor :name "LastForwardPoints" :description ""))
  (196 . ,(fix-tag-descriptor :name "AllocLinkID" :description ""))
  (197 . ,(fix-tag-descriptor :name "AllocLinkType" :description ""))
  (198 . ,(fix-tag-descriptor :name "SecondaryOrderID" :description ""))
  (199 . ,(fix-tag-descriptor :name "NoIOIQualifiers" :description ""))
  (200 . ,(fix-tag-descriptor :name "MaturityMonthYear" :description ""))
  (201 . ,(fix-tag-descriptor :name "PutOrCall" :description ""))
  (202 . ,(fix-tag-descriptor :name "StrikePrice" :description ""))
  (203 . ,(fix-tag-descriptor :name "CoveredOrUncovered" :description ""))
  (204 . ,(fix-tag-descriptor :name "CustomerOrFirm" :description ""))
  (205 . ,(fix-tag-descriptor :name "MaturityDay" :description ""))
  (206 . ,(fix-tag-descriptor :name "OptAttribute" :description ""))
  (207 . ,(fix-tag-descriptor :name "SecurityExchange" :description ""))
  (208 . ,(fix-tag-descriptor :name "NotifyBrokerOfCredit" :description ""))
  (209 . ,(fix-tag-descriptor :name "AllocHandlInst" :description ""))
  (210 . ,(fix-tag-descriptor :name "MaxShow" :description ""))
  (211 . ,(fix-tag-descriptor :name "PegDifference" :description ""))
  (212 . ,(fix-tag-descriptor :name "XmlDataLen" :description ""))
  (213 . ,(fix-tag-descriptor :name "XmlData" :description ""))
  (214 . ,(fix-tag-descriptor :name "SettlInstRefID" :description ""))
  (215 . ,(fix-tag-descriptor :name "NoRoutingIDs" :description ""))
  (216 . ,(fix-tag-descriptor :name "RoutingType" :description ""))
  (217 . ,(fix-tag-descriptor :name "RoutingID" :description ""))
  (218 . ,(fix-tag-descriptor :name "SpreadToBenchmark" :description ""))
  (219 . ,(fix-tag-descriptor :name "Benchmark" :description ""))
  (223 . ,(fix-tag-descriptor :name "CouponRate" :description ""))
  (231 . ,(fix-tag-descriptor :name "ContractMultiplier" :description ""))
  (262 . ,(fix-tag-descriptor :name "MDReqID" :description ""))
  (263 . ,(fix-tag-descriptor :name "SubscriptionRequestType" :description ""))
  (264 . ,(fix-tag-descriptor :name "MarketDepth" :description ""))
  (265 . ,(fix-tag-descriptor :name "MDUpdateType" :description ""))
  (266 . ,(fix-tag-descriptor :name "AggregatedBook" :description ""))
  (267 . ,(fix-tag-descriptor :name "NoMDEntryTypes" :description ""))
  (268 . ,(fix-tag-descriptor :name "NoMDEntries" :description ""))
  (269 . ,(fix-tag-descriptor :name "MDEntryType" :description ""))
  (270 . ,(fix-tag-descriptor :name "MDEntryPx" :description ""))
  (271 . ,(fix-tag-descriptor :name "MDEntrySize" :description ""))
  (272 . ,(fix-tag-descriptor :name "MDEntryDate" :description ""))
  (273 . ,(fix-tag-descriptor :name "MDEntryTime" :description ""))
  (274 . ,(fix-tag-descriptor :name "TickDirection" :description ""))
  (275 . ,(fix-tag-descriptor :name "MDMkt" :description ""))
  (276 . ,(fix-tag-descriptor :name "QuoteCondition" :description ""))
  (277 . ,(fix-tag-descriptor :name "TradeCondition" :description ""))
  (278 . ,(fix-tag-descriptor :name "MDEntryID" :description ""))
  (279 . ,(fix-tag-descriptor :name "MDUpdateAction" :description ""))
  (280 . ,(fix-tag-descriptor :name "MDEntryRefID" :description ""))
  (281 . ,(fix-tag-descriptor :name "MDReqRejReason" :description ""))
  (282 . ,(fix-tag-descriptor :name "MDEntryOriginator" :description ""))
  (283 . ,(fix-tag-descriptor :name "LocationID" :description ""))
  (284 . ,(fix-tag-descriptor :name "DeskID" :description ""))
  (285 . ,(fix-tag-descriptor :name "DeleteReason" :description ""))
  (286 . ,(fix-tag-descriptor :name "OpenCloseSettleFlag" :description ""))
  (287 . ,(fix-tag-descriptor :name "SellerDays" :description ""))
  (288 . ,(fix-tag-descriptor :name "MDEntryBuyer" :description ""))
  (289 . ,(fix-tag-descriptor :name "MDEntrySeller" :description ""))
  (290 . ,(fix-tag-descriptor :name "MDEntryPositionNo" :description ""))
  (291 . ,(fix-tag-descriptor :name "FinancialStatus" :description ""))
  (292 . ,(fix-tag-descriptor :name "CorporateAction" :description ""))
  (293 . ,(fix-tag-descriptor :name "DefBidSize" :description ""))
  (294 . ,(fix-tag-descriptor :name "DefOfferSize" :description ""))
  (295 . ,(fix-tag-descriptor :name "NoQuoteEntries" :description ""))
  (296 . ,(fix-tag-descriptor :name "NoQuoteSets" :description ""))
  (297 . ,(fix-tag-descriptor :name "QuoteAckStatus" :description ""))
  (298 . ,(fix-tag-descriptor :name "QuoteCancelType" :description ""))
  (299 . ,(fix-tag-descriptor :name "QuoteEntryID" :description ""))
  (300 . ,(fix-tag-descriptor :name "QuoteRejectReason" :description ""))
  (301 . ,(fix-tag-descriptor :name "QuoteResponseLevel" :description ""))
  (302 . ,(fix-tag-descriptor :name "QuoteSetID" :description ""))
  (303 . ,(fix-tag-descriptor :name "QuoteRequestType" :description ""))
  (304 . ,(fix-tag-descriptor :name "TotQuoteEntries" :description ""))
  (305 . ,(fix-tag-descriptor :name "UnderlyingIDSource" :description ""))
  (306 . ,(fix-tag-descriptor :name "UnderlyingIssuer" :description ""))
  (307 . ,(fix-tag-descriptor :name "UnderlyingSecurityDesc" :description ""))
  (308 . ,(fix-tag-descriptor :name "UnderlyingSecurityExchange" :description ""))
  (309 . ,(fix-tag-descriptor :name "UnderlyingSecurityID" :description ""))
  (310 . ,(fix-tag-descriptor :name "UnderlyingSecurityType" :description ""))
  (311 . ,(fix-tag-descriptor :name "UnderlyingSymbol" :description ""))
  (312 . ,(fix-tag-descriptor :name "UnderlyingSymbolSfx" :description ""))
  (313 . ,(fix-tag-descriptor :name "UnderlyingMaturityMonthYear" :description ""))
  (314 . ,(fix-tag-descriptor :name "UnderlyingMaturityDay" :description ""))
  (315 . ,(fix-tag-descriptor :name "UnderlyingPutOrCall" :description ""))
  (316 . ,(fix-tag-descriptor :name "UnderlyingStrikePrice" :description ""))
  (317 . ,(fix-tag-descriptor :name "UnderlyingOptAttribute" :description ""))
  (318 . ,(fix-tag-descriptor :name "UnderlyingCurrency" :description ""))
  (319 . ,(fix-tag-descriptor :name "RatioQty" :description ""))
  (320 . ,(fix-tag-descriptor :name "SecurityReqID" :description ""))
  (321 . ,(fix-tag-descriptor :name "SecurityRequestType" :description ""))
  (322 . ,(fix-tag-descriptor :name "SecurityResponseID" :description ""))
  (323 . ,(fix-tag-descriptor :name "SecurityResponseType" :description ""))
  (324 . ,(fix-tag-descriptor :name "SecurityStatusReqID" :description ""))
  (325 . ,(fix-tag-descriptor :name "UnsolicitedIndicator" :description ""))
  (326 . ,(fix-tag-descriptor :name "SecurityTradingStatus" :description ""))
  (327 . ,(fix-tag-descriptor :name "HaltReasonChar" :description ""))
  (328 . ,(fix-tag-descriptor :name "InViewOfCommon" :description ""))
  (329 . ,(fix-tag-descriptor :name "DueToRelated" :description ""))
  (330 . ,(fix-tag-descriptor :name "BuyVolume" :description ""))
  (331 . ,(fix-tag-descriptor :name "SellVolume" :description ""))
  (332 . ,(fix-tag-descriptor :name "HighPx" :description ""))
  (333 . ,(fix-tag-descriptor :name "LowPx" :description ""))
  (334 . ,(fix-tag-descriptor :name "Adjustment" :description ""))
  (335 . ,(fix-tag-descriptor :name "TradSesReqID" :description ""))
  (336 . ,(fix-tag-descriptor :name "TradingSessionID" :description ""))
  (337 . ,(fix-tag-descriptor :name "ContraTrader" :description ""))
  (338 . ,(fix-tag-descriptor :name "TradSesMethod" :description ""))
  (339 . ,(fix-tag-descriptor :name "TradSesMode" :description ""))
  (340 . ,(fix-tag-descriptor :name "TradSesStatus" :description ""))
  (341 . ,(fix-tag-descriptor :name "TradSesStartTime" :description ""))
  (342 . ,(fix-tag-descriptor :name "TradSesOpenTime" :description ""))
  (343 . ,(fix-tag-descriptor :name "TradSesPreCloseTime" :description ""))
  (344 . ,(fix-tag-descriptor :name "TradSesCloseTime" :description ""))
  (345 . ,(fix-tag-descriptor :name "TradSesEndTime" :description ""))
  (346 . ,(fix-tag-descriptor :name "NumberOfOrders" :description ""))
  (347 . ,(fix-tag-descriptor :name "MessageEncoding" :description ""))
  (348 . ,(fix-tag-descriptor :name "EncodedIssuerLen" :description ""))
  (349 . ,(fix-tag-descriptor :name "EncodedIssuer" :description ""))
  (350 . ,(fix-tag-descriptor :name "EncodedSecurityDescLen" :description ""))
  (351 . ,(fix-tag-descriptor :name "EncodedSecurityDesc" :description ""))
  (352 . ,(fix-tag-descriptor :name "EncodedListExecInstLen" :description ""))
  (353 . ,(fix-tag-descriptor :name "EncodedListExecInst" :description ""))
  (354 . ,(fix-tag-descriptor :name "EncodedTextLen" :description ""))
  (355 . ,(fix-tag-descriptor :name "EncodedText" :description ""))
  (356 . ,(fix-tag-descriptor :name "EncodedSubjectLen" :description ""))
  (357 . ,(fix-tag-descriptor :name "EncodedSubject" :description ""))
  (358 . ,(fix-tag-descriptor :name "EncodedHeadlineLen" :description ""))
  (359 . ,(fix-tag-descriptor :name "EncodedHeadline" :description ""))
  (360 . ,(fix-tag-descriptor :name "EncodedAllocTextLen" :description ""))
  (361 . ,(fix-tag-descriptor :name "EncodedAllocText" :description ""))
  (362 . ,(fix-tag-descriptor :name "EncodedUnderlyingIssuerLen" :description ""))
  (363 . ,(fix-tag-descriptor :name "EncodedUnderlyingIssuer" :description ""))
  (364 . ,(fix-tag-descriptor :name "EncodedUnderlyingSecurityDescLen" :description ""))
  (365 . ,(fix-tag-descriptor :name "EncodedUnderlyingSecurityDesc" :description ""))
  (366 . ,(fix-tag-descriptor :name "AllocPrice" :description ""))
  (367 . ,(fix-tag-descriptor :name "QuoteSetValidUntilTime" :description ""))
  (368 . ,(fix-tag-descriptor :name "QuoteEntryRejectReason" :description ""))
  (369 . ,(fix-tag-descriptor :name "LastMsgSeqNumProcessed" :description ""))
  (370 . ,(fix-tag-descriptor :name "OnBehalfOfSendingTime" :description ""))
  (371 . ,(fix-tag-descriptor :name "RefTagID" :description ""))
  (372 . ,(fix-tag-descriptor :name "RefMsgType" :description ""))
  (373 . ,(fix-tag-descriptor :name "SessionRejectReason" :description ""))
    (374 . ,(fix-tag-descriptor :name "BidRequestTransType" :description ""))
  (375 . ,(fix-tag-descriptor :name "ContraBroker" :description ""))
  (376 . ,(fix-tag-descriptor :name "ComplianceID" :description ""))
  (377 . ,(fix-tag-descriptor :name "SolicitedFlag" :description ""))
  (378 . ,(fix-tag-descriptor :name "ExecRestatementReason" :description ""))
  (379 . ,(fix-tag-descriptor :name "BusinessRejectRefID" :description ""))
  (380 . ,(fix-tag-descriptor :name "BusinessRejectReason" :description ""))
  (381 . ,(fix-tag-descriptor :name "GrossTradeAmt" :description ""))
  (382 . ,(fix-tag-descriptor :name "NoContraBrokers" :description ""))
  (383 . ,(fix-tag-descriptor :name "MaxMessageSize" :description ""))
  (384 . ,(fix-tag-descriptor :name "NoMsgTypes" :description ""))
  (385 . ,(fix-tag-descriptor :name "MsgDirection" :description ""))
  (386 . ,(fix-tag-descriptor :name "NoTradingSessions" :description ""))
  (387 . ,(fix-tag-descriptor :name "TotalVolumeTraded" :description ""))
  (388 . ,(fix-tag-descriptor :name "DiscretionInst" :description ""))
  (389 . ,(fix-tag-descriptor :name "DiscretionOffset" :description ""))
  (390 . ,(fix-tag-descriptor :name "BidID" :description ""))
  (391 . ,(fix-tag-descriptor :name "ClientBidID" :description ""))
  (392 . ,(fix-tag-descriptor :name "ListName" :description ""))
  (393 . ,(fix-tag-descriptor :name "TotalNumSecurities" :description ""))
  (394 . ,(fix-tag-descriptor :name "BidType" :description ""))
  (395 . ,(fix-tag-descriptor :name "NumTickets" :description ""))
  (396 . ,(fix-tag-descriptor :name "SideValue1" :description ""))
  (397 . ,(fix-tag-descriptor :name "SideValue2" :description ""))
  (398 . ,(fix-tag-descriptor :name "NoBidDescriptors" :description ""))
  (399 . ,(fix-tag-descriptor :name "BidDescriptorType" :description ""))
  (400 . ,(fix-tag-descriptor :name "BidDescriptor" :description ""))
  (401 . ,(fix-tag-descriptor :name "SideValueInd" :description ""))
  (402 . ,(fix-tag-descriptor :name "LiquidityPctLow" :description ""))
  (403 . ,(fix-tag-descriptor :name "LiquidityPctHigh" :description ""))
  (404 . ,(fix-tag-descriptor :name "LiquidityValue" :description ""))
  (405 . ,(fix-tag-descriptor :name "EFPTrackingError" :description ""))
  (406 . ,(fix-tag-descriptor :name "FairValue" :description ""))
  (407 . ,(fix-tag-descriptor :name "OutsideIndexPct" :description ""))
  (408 . ,(fix-tag-descriptor :name "ValueOfFutures" :description ""))
  (409 . ,(fix-tag-descriptor :name "LiquidityIndType" :description ""))
  (410 . ,(fix-tag-descriptor :name "WtAverageLiquidity" :description ""))
  (411 . ,(fix-tag-descriptor :name "ExchangeForPhysical" :description ""))
  (412 . ,(fix-tag-descriptor :name "OutMainCntryUIndex" :description ""))
  (413 . ,(fix-tag-descriptor :name "CrossPercent" :description ""))
  (414 . ,(fix-tag-descriptor :name "ProgRptReqs" :description ""))
  (415 . ,(fix-tag-descriptor :name "ProgPeriodInterval" :description ""))
  (416 . ,(fix-tag-descriptor :name "IncTaxInd" :description ""))
  (417 . ,(fix-tag-descriptor :name "NumBidders" :description ""))
  (418 . ,(fix-tag-descriptor :name "TradeType" :description ""))
  (419 . ,(fix-tag-descriptor :name "BasisPxType" :description ""))
  (420 . ,(fix-tag-descriptor :name "NoBidComponents" :description ""))
  (421 . ,(fix-tag-descriptor :name "Country" :description ""))
  (422 . ,(fix-tag-descriptor :name "TotNoStrikes" :description ""))
  (423 . ,(fix-tag-descriptor :name "PriceType" :description ""))
  (424 . ,(fix-tag-descriptor :name "DayOrderQty" :description ""))
  (425 . ,(fix-tag-descriptor :name "DayCumQty" :description ""))
  (426 . ,(fix-tag-descriptor :name "DayAvgPx" :description ""))
  (427 . ,(fix-tag-descriptor :name "GTBookingInst" :description ""))
  (428 . ,(fix-tag-descriptor :name "NoStrikes" :description ""))
  (429 . ,(fix-tag-descriptor :name "ListStatusType" :description ""))
  (430 . ,(fix-tag-descriptor :name "NetGrossInd" :description ""))
  (431 . ,(fix-tag-descriptor :name "ListOrderStatus" :description ""))
  (432 . ,(fix-tag-descriptor :name "ExpireDate" :description ""))
  (433 . ,(fix-tag-descriptor :name "ListExecInstType" :description ""))
  (434 . ,(fix-tag-descriptor :name "CxlRejResponseTo" :description ""))
  (435 . ,(fix-tag-descriptor :name "UnderlyingCouponRate" :description ""))
  (436 . ,(fix-tag-descriptor :name "UnderlyingContractMultiplier" :description ""))
  (437 . ,(fix-tag-descriptor :name "ContraTradeQty" :description ""))
  (438 . ,(fix-tag-descriptor :name "ContraTradeTime" :description ""))
  (439 . ,(fix-tag-descriptor :name "ClearingFirm" :description ""))
  (440 . ,(fix-tag-descriptor :name "ClearingAccount" :description ""))
  (441 . ,(fix-tag-descriptor :name "LiquidityNumSecurities" :description ""))
  (442 . ,(fix-tag-descriptor :name "MultiLegReportingType" :description ""))
  (443 . ,(fix-tag-descriptor :name "StrikeTime" :description ""))
  (444 . ,(fix-tag-descriptor :name "ListStatusText" :description ""))
  (445 . ,(fix-tag-descriptor :name "EncodedListStatusTextLen" :description ""))
  (446 . ,(fix-tag-descriptor :name "EncodedListStatusText" :description ""))))


(defun fix-translate-region (start end)
  (interactive "r")
  (fix-translate (buffer-substring (region-beginning) (region-end))))

(defun fix-translate (fixmessage)
  "Translate FIXMESSAGE and place into decode buffer."
  (interactive "sMessage:")
  (let* ((split (split-string fixmessage fix-field-separator-re t))
         (fields (mapcar (lambda (x) (split-string x fix-tag-separator-re t)) split))
         (buffer (get-buffer-create "*Message-Decode*")))
    (with-current-buffer buffer
      (goto-char (point-max))
      (org-mode)
      (insert "\n|Tag|Value|Description|\n")
      (insert "|-\n")
      (dolist (field fields)
        (unless (null field) (insert (fix--format-tag field))))
      (insert "|-")
      (org-table-align))))

(defun fix--format-tag (tagpair)
  "Format row given a pair of the tag and value in TAGPAIR."
  (let* ((tag (string-to-number (car tagpair)))
         (value (car (cdr tagpair)))
         (record (cdr (assoc tag fix-test-tags))))
    (if (null record)
        (format "|%s|%s|unknown|\n" tag value)
      (format "|%s(%s)|%s|%s|\n" (oref record :name) tag value (oref record :description)))))

(provide 'fix)
;;; fix.el ends here
